=== profesorderedes/Lenguajes-de-marcas/Tema3/ejemplos/ejemplo04.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="receta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="medicamento" maxOccurs="unbounded" />
                <xs:element ref="farmacia" />
                <xs:element ref="edad" />
                <xs:element ref="nombre" />
                <xs:element ref="pago" />
                <xs:element ref="dni" />
                <xs:element ref="precio" />
                <xs:element ref="medico" />
                <xs:element ref="posologia" />
                <xs:element ref="alergia" />
                <xs:element ref="grupo_sanguineo" />
                <xs:element ref="instrucciones" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="medicamento" type="xs:string" />

    <xs:element name="farmacia" type="xs:string" default="Farmacia Juaneda" />

    <xs:element name="edad">
        <xs:simpleType>
            <xs:restriction base="xs:nonNegativeInteger">
                <xs:maxInclusive value="125" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="nombre">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="3" />
                <xs:maxLength value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="pago">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Gratuito" />
                <xs:enumeration value="Copago" />
                <xs:enumeration value="Entero" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="dni">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="\d{8}[a-zA-Z]" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="precio">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="medico">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="numColegiado" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="numColegiado" type="xs:positiveInteger" />

    <xs:element name="posologia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tomas" />
                <xs:element ref="horario" />
            </xs:sequence>
            <xs:attribute ref="duracion" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="duracion" type="xs:string" />

    <xs:element name="tomas">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:maxInclusive value="8" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="horario" type="xs:string" />

    <xs:element name="alergia">
        <xs:complexType />
    </xs:element>

    <xs:element name="grupo_sanguineo">
        <xs:complexType>
            <xs:attribute ref="tipo" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="tipo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="0+" />
                <xs:enumeration value="0-" />
                <xs:enumeration value="A+" />
                <xs:enumeration value="A-" />
                <xs:enumeration value="B+" />
                <xs:enumeration value="B-" />
                <xs:enumeration value="AB+" />
                <xs:enumeration value="AB-" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="instrucciones">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="b" />
                <xs:element ref="i" />
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="b" type="xs:string" />

    <xs:element name="i" type="xs:string" />

</xs:schema>

=== profesorderedes/Lenguajes-de-marcas/Tema3/ejemplos/ejemplo04.xml
<?xml version="1.0" encoding="UTF-8"?>

<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejemplo04.xsd">

    <medicamento>Paracetamol</medicamento>
    <medicamento>Omeprazol</medicamento>

    <farmacia>Farmacia Juaneda</farmacia>

    <edad>70</edad>

    <nombre>Francisco Santos</nombre>

    <pago>Gratuito</pago>

    <dni>10918186q</dni>

    <precio>16.51</precio>

    <medico numColegiado="171612713">Juan Ríos</medico>

    <posologia duracion="Cinco días">
        <tomas>3</tomas>
        <horario>Mañana, tarde y noche</horario>
    </posologia>

    <alergia />

    <grupo_sanguineo tipo="AB-" />

    <instrucciones>Esta medicación debe tomarse en <b>ayunas</b>. No <i>deben superarse</i> los <b>cuatro</b>
        comprimidos al día. </instrucciones>

</receta>
