=== profesorderedes/Lenguajes-de-marcas/Tema3/ejemplos/ejemplo02.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="taller">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="coche" type="xs:string" minOccurs="0" maxOccurs="unbounded" />

                <xs:element name="nombre_taller" fixed="Motor Son Ferrer" />

                <xs:element name="antiguedad">
                    <xs:simpleType>
                        <xs:restriction base="xs:nonNegativeInteger">
                            <xs:maxInclusive value="120" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="propietario">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="5" />
                            <xs:maxLength value="40" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="tipo_empresa">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Autónomo" />
                            <xs:enumeration value="SL" />
                            <xs:enumeration value="SA" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="tarifa_pinchazos">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:fractionDigits value="2" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="mecanico">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="dni" type="xs:string" use="required" />
                                <xs:attribute name="titulacion" type="xs:string" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="isla">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="Mallorca" type="xs:string" />
                            <xs:element name="Menorca" type="xs:string" />
                            <xs:element name="Ibiza" type="xs:string" />
                            <xs:element name="Formentera" type="xs:string" />
                        </xs:choice>
                    </xs:complexType>
                </xs:element>

                <xs:element name="multimarca" minOccurs="0">
                    <xs:complexType />
                </xs:element>

                <xs:element name="categoria" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="tipo" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="descripcion">
                    <xs:complexType mixed="true">
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="i" type="xs:string" />
                            <xs:element name="b" type="xs:string" />
                        </xs:choice>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== profesorderedes/Lenguajes-de-marcas/Tema3/ejemplos/ejemplo02.xml
<?xml version="1.0" encoding="UTF-8"?>

<taller xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejemplo02.xsd">

    <coche>Peugeot 206</coche>
    <coche>Seat Ibiza</coche>
    <coche>Volkswagen Golf</coche>

    <nombre_taller>Motor Son Ferrer</nombre_taller>

    <!-- La antigüedad estará entre 0 y 120, ambos inclusive -->
    <antiguedad>20</antiguedad>

    <!-- El nombre del propietario tendrá entre 5 y 40 caracteres -->
    <propietario>Manuel Antonio López</propietario>

    <!-- Tipo de empresa: Autónomo, SL, SA -->
    <tipo_empresa>Autónomo</tipo_empresa>

    <!-- La tarifa de reparación de un pinchazo es de 10,5 euros  -->
    <tarifa_pinchazos>10.5</tarifa_pinchazos>

    <!-- El dni es un atributo obligatorio y la titulación no lo es -->
    <mecanico dni="20199299R" titulacion="grado superior">Jaime Pérez</mecanico>

    <!-- Dentro de isla puede aparecer el nombre de alguna de las islas de Baleares -->
    <isla>
        <Formentera />
    </isla>

    <!-- La etiqueta "multimarca" indica que el taller no es
     un concesionario oficial -->
    <multimarca/>

    <!-- Pueden haber 0 o más etiquetas categoría, que siempre
     estarán vacías con un atributo tipo. -->
    <categoria tipo="ChapaYPintura" />
    <categoria tipo="Electromecánica" />
    <categoria tipo="Estructura" />

    <descripcion>
        El taller se encuentra en la <i>calle Cóndor, 9</i>, y realiza trabajos de todo tipo, especialmente <b>chapa y pintura</b>, <b>electromecánica</b> y <b>estructura</b>.
    </descripcion>

</taller>
