=== profesorderedes/Lenguajes-de-marcas/Tema3/ejemplos/ejemplo01.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="receta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="medicamento" type="xs:string" minOccurs="1" maxOccurs="unbounded" />

                <xs:element name="farmacia" default="Farmacia Juaneda" />

                <xs:element name="edad">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="0" />
                            <xs:maxInclusive value="125" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3" />
                            <xs:maxLength value="30" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="pago">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Integro" />
                            <xs:enumeration value="Copago" />
                            <xs:enumeration value="Gratuito" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="dni">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d{8}[a-zA-Z]" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

                <xs:element name="precio">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:fractionDigits value="2" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== profesorderedes/Lenguajes-de-marcas/Tema3/ejemplos/ejemplo01.xml
<?xml version="1.0" encoding="UTF-8"?>

<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejemplo01.xsd">

    <medicamento>Paracetamol</medicamento>
    <medicamento>Omeprazol</medicamento>

    <farmacia>Farmacia Juaneda</farmacia>

    <edad>70</edad>

    <nombre>Francisco Santos</nombre>

    <pago>Gratuito</pago>

    <dni>10918186q</dni>

    <precio>16.51</precio>

    <medico numColegiado="171612713">Juan Ríos</medico>

</receta>
