=== profesorderedes/Lenguajes-de-marcas/Tema3/ejercicios/ejerciciosXSD/ejer03.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="tourGuide" />

    <xs:element name="city" />

    <xs:element name="adminUnit" />

    <xs:element name="country" />

    <xs:element name="population" />

    <xs:element name="area" />

    <xs:element name="elevation" />

    <xs:element name="longitude" />

    <xs:element name="latitude" />

    <xs:element name="description" />
    
    <xs:element name="history" />

</xs:schema>

=== profesorderedes/Lenguajes-de-marcas/Tema3/ejercicios/ejerciciosXSD/ejer03.xml
<?xml version="1.0" encoding="UTF-8"?>

<tourGuide xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejer03.xsd">

    <city>
        <cityName>Belmopan</cityName>
        <adminUnit>Cayo</adminUnit>
        <country>Belize</country>
        <population>11100</population>
        <area>5</area>
        <elevation>130</elevation>
        <longitude>88.44</longitude>
        <latitude>17.27</latitude>
        <description>Belmopan is the capital of Belize</description>
        <history>Belmopan was established following the devastation of the
            former capital, Belize City, by Hurricane Hattie in 1965. High
            ground and open space influenced the choice and ground-breaking
            began in 1966. By 1970 most government offices and operations had
            already moved to the new location.
</history>
    </city>

    <city>
        <longitude>101.71</longitude>
        <latitude>3.16</latitude>
        <cityName>Kuala Lumpur</cityName>
        <country>Malaysia</country>
        <population>1448600</population>
        <area>243</area>
        <adminUnit>Selangor</adminUnit>
        <elevation>111</elevation>
        <description>Kuala Lumpur is the capital of Malaysia and the largest
            city in the nation</description>
        <history>The city was founded in 1857 by Chinese tin miners and
            preceded Klang. In 1880 the British government transferred their
            headquarters from Klang to Kuala Lumpur, and in 1896 it became the
            capital of Malaysia.
</history>
    </city>

    <city>
        <cityName>Winnipeg</cityName>
        <adminUnit>St. Boniface</adminUnit>
        <country>Canada</country>
        <population>618512</population>
        <area>124</area>
        <elevation>40</elevation>
        <longitude>97.14</longitude>
        <latitude>49.54</latitude>
        <description>Winnipeg has two seasons. Winter and Construction.</description>
        <history>The city was founded by people at the forks (Fort Garry)
            trading in pelts with the Hudson Bay Company. Ironically,
            The Bay was bought by America.
</history>
    </city>

</tourGuide>
