=== profesorderedes/Lenguajes-de-marcas/Tema3/ejercicios/prac2/control_acceso.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="control_acceso">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="personal" />
                <xs:element ref="ubicaciones" />
                <xs:element ref="mensaje_error" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="personal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="persona" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="persona">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="acceso" />
            </xs:sequence>
            <xs:attribute ref="cargo" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="cargo" default="empleado">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="director" />
                <xs:enumeration value="jefe" />
                <xs:enumeration value="empleado" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="nombre">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="5" />
                <xs:maxLength value="30" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="acceso">
        <xs:complexType>
            <xs:attribute ref="cod_ubicaciones" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="cod_ubicaciones" type="xs:IDREFS" />

    <xs:element name="ubicaciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ubicacion" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ubicacion">
        <xs:complexType>
            <xs:all>
                <xs:element ref="nombre" />
                <xs:element ref="planta" />
            </xs:all>
            <xs:attribute ref="nivel_seguridad" use="required" />
            <xs:attribute ref="codigo" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="nivel_seguridad">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:maxInclusive value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="codigo">
        <xs:simpleType>
            <xs:restriction base="xs:ID">
                <xs:pattern value="[A-Z]{1,3}\d" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="planta" type="xs:nonNegativeInteger" />

    <xs:element name="mensaje_error">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="b" />
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="b" type="xs:string" />

</xs:schema>

=== profesorderedes/Lenguajes-de-marcas/Tema3/ejercicios/prac2/control_acceso.xml
<?xml version="1.0" encoding="UTF-8"?>

<control_acceso xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="control_acceso.xsd">

    <personal>

        <persona cargo="director">
            <nombre>María Ochoa Rodríguez</nombre>
            <acceso cod_ubicaciones="SCT1 LV1 CC3 AMO7" />
        </persona>

        <persona cargo="jefe">
            <nombre>Laura Vallés García</nombre>
            <acceso cod_ubicaciones="SCT1 LV1 AMO7" />
        </persona>

        <persona cargo="empleado">
            <nombre>Rocío Ortega Jiménez</nombre>
            <acceso cod_ubicaciones="SCT1 LV1" />
        </persona>

        <persona cargo="empleado">
            <nombre>Lorena Gil Marqués</nombre>
            <acceso cod_ubicaciones="SCT1 CC3" />
        </persona>

    </personal>

    <ubicaciones>

        <ubicacion nivel_seguridad="1" codigo="SCT1">
            <nombre>Sala común de trabajo</nombre>
            <planta>0</planta>
        </ubicacion>

        <ubicacion nivel_seguridad="20" codigo="LV1">
            <planta>1</planta>
            <nombre>Laboratorio vírico nº1</nombre>
        </ubicacion>

        <ubicacion nivel_seguridad="3" codigo="CC3">
            <nombre>Centro de computación</nombre>
            <planta>2</planta>
        </ubicacion>

        <ubicacion nivel_seguridad="20" codigo="AMO7">
            <nombre>Almacén de muestras orgánicas</nombre>
            <planta>1</planta>
        </ubicacion>

    </ubicaciones>

    <mensaje_error>No tiene acceso a esta ubicación. <b>Póngase en contacto con el administrador de
        la red.</b></mensaje_error>

</control_acceso>
