=== profesorderedes/Lenguajes-de-marcas/Tema3/ejercicios/hoja1/ejer01.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="factura" />

    <xs:attribute name="codigo" />

    <xs:attribute name="estado" />

    <xs:element name="cliente" />

    <xs:element name="nombre" />

    <xs:element name="articulos" />

    <xs:element name="articulo" />

    <xs:attribute name="iva" />

    <xs:element name="descripcion" />

    <xs:element name="precioUnitario" />
    
    <xs:element name="unidades" />

</xs:schema>

=== profesorderedes/Lenguajes-de-marcas/Tema3/ejercicios/hoja1/ejer01.xml
<?xml version="1.0" encoding="UTF-8"?>

<factura codigo="7190" estado="pagado"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejer01.xsd">

    <cliente>
        <nombre>Mariano Pérez</nombre>
    </cliente>
    
    <articulos>
        <articulo iva="21">
            <descripcion>Pendrive 16GB TDK</descripcion>
            <precioUnitario>9.50</precioUnitario>
            <unidades>2</unidades>
        </articulo>
        <articulo iva="16">
            <descripcion>Paquete de 500 folios Ofimarket 80g</descripcion>
            <precioUnitario>6.25</precioUnitario>
            <unidades>1</unidades>
        </articulo>
        <articulo iva="16">
            <descripcion>Calculadora Casio científica</descripcion>
            <precioUnitario>12.00</precioUnitario>
            <unidades>1</unidades>
        </articulo>
    </articulos>
</factura>
