=== profesorderedes/Lenguajes-de-marcas/Tema2/ejemplos/ejemplo09.dtd
<!ELEMENT taller (coche*, reparacion*)>
<!ELEMENT coche (marca, modelo)>
<!ATTLIST coche fecha_entrada NMTOKEN #REQUIRED>
<!ATTLIST coche fechas_revisiones NMTOKENS #REQUIRED>
<!ATTLIST coche matricula ID #REQUIRED>

<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT reparacion (concepto, precio)>
<!ATTLIST reparacion mat_vehiculo IDREF #REQUIRED>

<!ELEMENT concepto (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== profesorderedes/Lenguajes-de-marcas/Tema2/ejemplos/ejemplo09.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE taller SYSTEM "ejemplo09.dtd">
<taller>
    <coche matricula="MAT-1001BVC" fecha_entrada="2023-10-01"
        fechas_revisiones="2021-01-25 2022-01-28 2023-02-05">
        <marca>Kia</marca>
        <modelo>Stonic</modelo>
    </coche>

    <coche matricula="MAT-8329GHA" fecha_entrada="2023-10-01"
        fechas_revisiones="2021-01-25 2022-01-28 2023-02-05">
        <marca>Kia</marca>
        <modelo>Stonic</modelo>
    </coche>

    <reparacion mat_vehiculo="MAT-8329GHA">
        <concepto>Pinchazo rueda trasera izquiera</concepto>
        <precio>10</precio>
    </reparacion>
</taller>
