=== profesorderedes/Lenguajes-de-marcas/Tema2/ejemplos/ejemplo10.dtd
<!ELEMENT cartelera (actor*, pelicula*)>
<!ELEMENT actor (#PCDATA)>
<!ATTLIST actor cod ID #REQUIRED>

<!ELEMENT pelicula (#PCDATA)>
<!ATTLIST pelicula actores IDREFS #REQUIRED>

=== profesorderedes/Lenguajes-de-marcas/Tema2/ejemplos/ejemplo10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartelera SYSTEM "ejemplo10.dtd">

<cartelera>

    <actor cod="HF">Harrison Ford</actor>
    <actor cod="SW">Sigourney Weaver</actor>
    <actor cod="BP">Bill Paxton</actor>
    <actor cod="MB">Michael Biehn</actor>
    <actor cod="AS">Arnold Schwarzenegger</actor>

    <pelicula actores="HF">En busca del arca perdida</pelicula>
    <pelicula actores="SW BP MB">Aliens, el regreso</pelicula>
    <pelicula actores="AS MB">Terminator</pelicula>

</cartelera>
